# Algebraic Geometry {#algebraic-geometry}

## Construction

An `r term("complex affine algebraic variety")` or just a variety is the `r preq("zero locus")` zero locus of a finite set of polynomials. `r term("Affine n-space")` $\mathbb{A}^n$ is $\mathbb{C}^n$ endowed with the `r term("Zariski topoplogy")` wherein open sets are complements of varieties. We use the notation $\mathbb{V}(F_i)$ to denote the variety defined by the zero locus of the polynomials $F_i : \mathbb{A}^n \to \mathbb{C}$. Morphisms of varieties are restrictions of polynomial maps between affine spaces, and are continuous in the Zariski topology. An `r term("irreducible variety")` is a variety which cannot be expressed non-trivially as the union of two varieties: this enables the notion of the dimension of a variety, namely the longest chain of proper inclusions of its subvarieties (the number of inclusions, not the number of sets).

## Commutative Ring Theory Interlude

For our purposes, a `r term("commutative ring")`, or just a ring, is a set endowed with the structure of an Abelian group (with operation known as "addition") and a monoid (with operation known as "multiplication") such that the latter operation distributes over the former. `r term("Ring homomorphisms")` preserve both structures and the identity element.

An `r term("ideal")` is a subset of a ring which is closed under addition and invariant under multiplication. The ideal generated by some elements is the intersection of all ideals containing those elements. The `r term("radical")` $\sqrt{I}$ of an ideal $I$ is the set of elements which possess a power belonging to the ideal. An ideal is `r term("maximal")` if the only ideal properly containing it is the whole ring, `r term("prime")` if a product only belongs to it when both elements of the product belong to it, `r term("radical")` if it coincides with its radical, and `r term("reduced")` if it contains no nilpotent elements.

Rings can be quotiented by ideals, and the canonical surjection maps ideals containing the quotienting ideal to ideals in the quotient (preserving maximality, primeness and radicalness). A quotient is a `r term("field")` (multiplication has inverses) if and only if the ideal is maximal and a `r term("domain")` (there exist no `r term("zero-divisors")`, or non-zero elements mapping other non-zero elements to zero via multiplication) if and only if the ideal is prime. In particular, maximal ideals are prime. Moreover, prime ideals are radical and quotients are reduced if and only if the ideal is radical.

A `r term("$\\mathbb{C}$-algebra")` is a ring containing $\mathbb{C}$, and suitable notions of homomorphism, etc. follow naturally. A `r term("Noetherian ring")` is a finitely generated ring, and Hilbert's basis theorem states that the rings of polynomials $\mathbb{C}[x_1, \dots, x_n]$ are Noetherian.

## Algebra-Geometry Correspondence

Let $\mathbb{I}(V)$ denote the ideal of polynomials vanishing on the variety $V$. Immediately, we see that $\mathbb{V}(\mathbb{I}(V)) = V$, so $\mathbb{V}$ is a left inverse $\mathbb{I}$ to. Hilbert's Nullstellensatz reveals that $\mathbb{V}$ is also a partial right inverse: in particular, let $I$ by a polynomial ideal, then $\mathbb{I}(\mathbb{V}(I)) = \sqrt{I}$. In particular, $\mathbb{V}$ is a right inverse on radical ideals; said differently, the Nullstellensatz induces a bijection between varieties and radical ideals in $\mathbb{C}[x_1, \dots, x_n]$[^com:nullstellensatz_interp].

This has many corollaries. For instance, varieties are finite-dimensional; varieties are the zero locus of finitely many polynomials (in particular, the intersection of finitely many hypersurfaces); $\mathbb{I}(V)$ is radical; and prime ideals are in bijection with irreducible varieties.

Consider the `r term("coordinate ring")` $\mathbb{C}[V]$ of polynomials on $V$. This is $\mathbb{C}[x_1, \dots, x_n]/\mathbb{I}(V)$, hence it is a reduced, finitely generated $\mathbb{C}$-algebra. Variety morphisms induce (direction-reversing) morphisms between coordinate rings. The connection between varieties and coordinate rings is a bijection: namely, there is an equivalence (up to arrow-reversing) between the category of varieties and the category of finitely generated reduced $\mathbb{C}$-algebras.

[^com:nullstellensatz_interp]: Alternatively, we can interpret this by defining an equivalence relationship on the ideals of $\mathbb{C}[x_1, \dots, x_n]$ by defining similarity between ideals sharing a radical and observing that the cosets of the quotient given by this equivalence are placed in bijection with varieties. This is equivalent to the given interpretation, which merely chooses that radical itself to be a candidate for the coset.
