# Algebraic Topology

## Simplicial Homology

An `r term("$n$-simplex")` $p = \langle p_1 \dots p_n \rangle$ is an ordered list of points representing its (oriented, or signed) convex hull of the points $p_i$. A `r term("$q$-face")` is the convex hull specified by $q + 1$ of the $p_i$. A `r term("simplicial complex")` $K$ is the finite union of $n$-simplexes (for possibly varying $n$) which is closed under taking faces and non-trivial intersections of two elements is a common face. The `r term("$r$-chain group")` $C_r(K)$ is the free Abelian group generated by the $r$-simplexes of $K$: elements are `r term("$r$-chains")`. The `r term("boundary operators")` $\partial_{r} : C_{r}(K) \to C_{r-1}(K)$ are defined by the linear extensions of
\begin{equation}
    \langle p_0 \dots p_r \rangle \mapsto \sum_i (-1)^i (p_0 \dots \hat{p}_i \dots p_r).
\end{equation}
The `r term("chain complex")` for $K$ is the induced long exact sequence
\begin{equation}
    0 \to C_n(K) \to \dots \to C_1(K) \to C_0(K) \to 0
\end{equation}
The `r term("$r$-cycle group")` $Z_r(K)$ (containing `r term("$r$-cycles")`) and the `r term("$r$-boundary group")` $B_r(K)$ (containing `r term("$r$-boundaries")`) are the kernel of $\partial_r$ and the image of $\partial_{r+1}$, respectively. In particular, $\partial_{r} \circ \partial_{r+1} = 0$ so $B_r(K) \subset Z_r(K)$ and the quotient $Z_r(K)/B_r(K)$ is the `r term("$r$th homology group")` associated to $K$, whose elements are known as `r term("homnology classes")`
