# Lie Theory

## Lie Algebras

Let $G$ be a Lie group. 
A vector field $X$ on $G$ satisfying $(L_g)_* X = X \circ L_g$ is called `r term("left invariant")`.
The `r term("Lie algebra")` to $G$, $\mathfrak{g}$, is the set of all left-invariant vector fields on $G$; the name is natural as the Lie bracket induces a Lie algebraic structure on this set. 
Note that $\mathfrak{g}$ is naturally isomorphic to $T_e G$, where $e$ is the identity element, as $Y \in T_e G$ induces a vector field $X$ given by $X_g = (L_g)_* Y$; in particular, this means $\dim \mathfrak{g} = \dim G$. 
Given a basis $X_1, \dots, X_n$ of $\mathfrak{g}$, we have that $[X_i, X_j] = c_{ij}^h X_h$ and we say the $c_{ij}^h$ are the `r term("structure constants")` associated with the basis. 
Identifying $\mathfrak{g} \cong T_e G$[^com:lie_alg_identify] there is a natural $\mathfrak{g}$-valued one-form $\theta$ on $G$ defined by $v \mapsto (L_{g^{-1}})_*(v)$ for $v \in T_g G$. 
We call this the `r term("Maurer-Cartan one-form")` and it satisfies $d\theta + \frac{1}{2}[\theta, \theta]$.
Noting that, if $G$ is a matrix Lie group, $(L_g)_*$ coincides with the natural matrix multiplication action of the matrix $g$ on $TG$, we have that $\theta(v) = g^{-1}v$ where the right hand side is matrix multiplication[^com:maurer_cartan_matrix_lie_group]. 

## Exponential Map 

A `r term("one-parameter subgroup")` on $G$ is a continuous group homomorphism $\mathbb{R} \to G$. For $X \in \mathfrak{g}$, let $\phi_{X,t} : G \to G$ be the associated flow, and let $g_X(t) = \phi_{X,t}(e) \in G$; then $g_X$ is a one parameter subgroup on $G$ (i.e., $g_X(t)g_X(s) = g_S(t+s)$).
Moreover, we have the `r term("exponential map")` $\exp : \mathfrak{g} \to G$ given by $X \mapsto g_X(1)$. 
From this it follows that $g_X(t) = \exp(tX)$; indeed, this is the most general form for a one parameter group.

## Adjoint Representation

[^com:lie_alg_identify]: TODO: clarify this identification

[^com:maurer_cartan_matrix_lie_group]: If we let $G$ be embedded in a matrix Lie group by a map $\phi$, then the Maurer-Carten form on $\phi(G)$ is $\theta = \phi(g^{-1})\phi_*$.
